on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build BE Image
        run: docker build --target production-be -t translation-api .

      - name: Build FE Image
        run: docker build --target production-fe -t translation-app .
        

      - name: Push to github container registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag translation-api ghcr.io/translation-app/translation-api:latest
          docker tag translation-app ghcr.io/translation-app/translation-app:latest
          docker push ghcr.io/translation-app/translation-api:latest
          docker push ghcr.io/translation-app/translation-app:latest

      
