name: lokla-actions
description: Upload your translation files to Lokla
author: Lokla
branding:
  icon: globe
  color: green
inputs:
  project-id:
    description: 'Project ID / Identifier'
    required: true
    default: 'lokla'
  endpoint:
    description: 'Endpoint'
    required: true
    default: 'https://lokla.mirfanrafif.my.id'
  api-key:
    description: 'API Key'
    required: true
    default: '1234567890'
  main-branch:
    description: 'Main branch'
    required: true
    default: 'main'
  directory:
    description: 'Directory'
    required: true
    default: 'public/locales'
runs:
  using: composite
  steps:
    # set as executable
    - name: Set as executable
      shell: bash
      run: chmod +x ${{ github.action_path }}/cli/upload.sh

    # run the upload script
    - run: ${{ github.action_path }}/cli/upload.sh
      shell: bash
      env:
        PROJECT_ID: ${{ inputs.project-id }}
        ENDPOINT: ${{ inputs.endpoint }}
        API_KEY: ${{ inputs.api-key }}
        MAIN_BRANCH: ${{ inputs.main-branch }}
        DIRECTORY: ${{ inputs.directory }}
      
      