services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: production-fe
    ports:
      - '3000:3000'
    networks:
      - default
    env_file:
      - .env

  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
      target: production-be
    ports:
      - '3001:3000'
    depends_on:
      - mongo
    networks:
      - default
    env_file:
      - .env

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - default
    env_file:
      - .env
    volumes:
      - mongodata:/data/db

networks:
  default:
    driver: bridge

volumes:
  mongodata:
    driver: local
