services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: production-fe
    ports:
      - '3000:3000'
    networks:
      - default

  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
      target: production-be
    ports:
      - '3001:3000'
    depends_on:
      - mongodb
    networks:
      - default

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - default

networks:
  default:
    driver: bridge
