version: '3'
services:
  translation-fe:
    container_name: translation-fe
    image: ghcr.io/mirfanrafif/lokla-app:latest
    env_file:
      - .env
    ports:
      - 4200:3000

networks:
  default:
    name: example_dev_network
    driver: bridge

volumes:
  mongodata:
