import classNames from 'classnames';
import { Noto_Sans, Noto_Sans_JP } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import Popup from 'apps/translation-app/components/Popup/Popup';
import PopupContextProvider from 'apps/translation-app/context/PopupProvider';

import './global.scss';

export const metadata = {
  title: 'Welcome to apps/translation-app',
  description: 'Generated by create-nx-workspace',
};

const notoSans = Noto_Sans({
  subsets: ['latin'],
});

const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(notoSans.className, notoSansJp.className)}>
        <PopupContextProvider>
          {children}
          <Toaster position="bottom-center" />
          <Popup />
        </PopupContextProvider>
      </body>
    </html>
  );
}
