on:
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1
        with: 
          platforms: linux/amd64,linux/arm64/v8

      - name: Build BE Image
        run: docker build --target production-be -t translation-api .

      - name: Build FE Image
        run: docker build --target production-fe -t translation-app .

      - name: Push to github container registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag translation-api ghcr.io/mirfanrafif/lokla-api:preview-$(echo $GITHUB_SHA | cut -c1-7)
          docker tag translation-app ghcr.io/mirfanrafif/lokla-app:preview-$(echo $GITHUB_SHA | cut -c1-7)
          docker push ghcr.io/mirfanrafif/lokla-api:preview-$(echo $GITHUB_SHA | cut -c1-7)
          docker push ghcr.io/mirfanrafif/lokla-app:preview-$(echo $GITHUB_SHA | cut -c1-7)
