on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build BE Image
        run: docker buildx build --target production-be -t translation-api --platform linux/amd64,linux/arm64/v8 .

      - name: Build FE Image
        run: docker buildx build --target production-fe -t translation-app --platform linux/amd64,linux/arm64/v8 .

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Push to github container registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag translation-api ghcr.io/mirfanrafif/lokla-api:latest
          docker tag translation-app ghcr.io/mirfanrafif/lokla-app:latest
          docker push ghcr.io/mirfanrafif/lokla-api:latest
          docker push ghcr.io/mirfanrafif/lokla-app:latest

        

      
