on:
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build BE Image
        run: docker build --target production-be -t translation-api .

      - name: Build FE Image
        run: docker build --target production-fe -t translation-app .

      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to fly
        run: |
          flyctl deploy -i ghcr.io/mirfanrafif/lokla-api:preview-$(echo $GITHUB_SHA | cut -c1-7) -i ghcr.io/mirfanrafif/lokla-app:preview-$(echo $GITHUB_SHA | cut -c1-7)
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        

      
